service: esa-source-lambda
provider:
  name: aws
  runtime: python3.8
  environment:
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    GITHUB_REPOSITORY: ${env:GITHUB_REPOSITORY}
    BRANCH_NAME: ${env:BRANCH_NAME}
    COMMIT_DIR: ${env:COMMIT_DIR}

functions:
  main:
    name: esa-source-lambda-${env:FUNC_NAME}-blog
    handler: handler.main
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
